### ISSUE TITLE
Issue importing go-vindalu-client

### ISSUE THREAD

**Issue by 45cali** [vindalu/go-vindalu-client#3]
[xxxxxxxxxxxx 45cali]$ go get github.com/vindalu/go-vindalu-client
# github.com/vindalu/vindalu/core

../vindalu/vindalu/core/utils.go:199: undefined: elastigo.Range
../vindalu/vindalu/core/utils.go:201: undefined: elastigo.Range
../vindalu/vindalu/core/utils.go:233: cannot use filterOps (type []interface {}) as type *elastigo.FilterOp in argument to elastigo.Search(index).Filter
../vindalu/vindalu/core/utils.go:233: invalid use of ... in call to elastigo.Search(index).Filter

**Comment by euforia** [comment]
The master branch for elastigo points to elasticsearch 2.0. Go to the elastigo folder and revert to this commit `451c29b3ae220cd710294bc3436e293d99491b94`

**Comment by 45cali** [comment]
worked perfect

**Comment by euforia** [comment]
i'll be adding `Godeps` in the future to make this easier.
